apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-mongo
spec:
  selector:
    matchLabels:
      run: my-mongo
  replicas: 1
  template:
    metadata:
      labels:
        run: my-mongo
    spec:
      containers:
        - name: my-mongo
          image: mongo
          ports:
          - containerPort: 27017
          env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongodbsecret
                key: mongo-root-username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodbsecret
                key: mongo-root-password